{% set name = "hepdata-lib" %}
{% set version = "0.18.0" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hepdata_lib-{{ version }}.tar.gz
  sha256: f89c154708fbcbf193e505b724ed17b315d837ba2cbda9b82e5bc1f3c77fa90e

build:
  # Will fail on Windows as imagemagick does not support Windows builds, but
  # failing on a noarch is preferred by the conda-forge maintainers
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml >=4.0
    - future
    - hist
    - scipy
    - hepdata-validator >=0.3.5
    - imagemagick
    # Treat ROOT as an optional dependency and so don't include it

test:
  imports:
    - hepdata_lib
  commands:
    - pip check
    - convert --version
    # TODO: Add test suite checks with ROOT
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HEPData/hepdata_lib
  summary: Library for getting your data into HEPData
  doc_url: https://hepdata-lib.readthedocs.io/
  dev_url: https://github.com/HEPData/hepdata_lib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - clelange
    - matthewfeickert
