{% set name = "hepdata-lib" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hepdata_lib-{{ version }}.tar.gz
  sha256: 22b7c188551333025394b83cbc981700ffd0ef7ddfb91708274b9ff496a54a14

build:
  # Will fail on Windows as imagemagick does not support Windows builds, but
  # failing on a noarch is preferred by the conda-forge maintainers
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pyyaml >=4.0
    - future
    - hist
    - scipy
    - hepdata-validator >=0.3.5
    - imagemagick
    # Treat ROOT as an optional dependency and so don't include it

test:
  imports:
    - hepdata_lib
  commands:
    - pip check
    - convert --version
    # TODO: Add test suite checks with ROOT
  requires:
    - pip

about:
  home: https://github.com/HEPData/hepdata_lib
  summary: Library for getting your data into HEPData
  doc_url: https://hepdata-lib.readthedocs.io/
  dev_url: https://github.com/HEPData/hepdata_lib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - clelange
    - matthewfeickert
