schema_version: 1

context:
  name: hepdata-lib
  version: "0.20.0"
  python_min: "3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hepdata_lib-${{ version }}.tar.gz
  sha256: f906783e5eb62d16bea3e7f97e1f8f5dcdd3782db7f50376b7f81e3bb136d55d

build:
  # Will fail on Windows as imagemagick does not support Windows builds, but
  # failing on a noarch is preferred by the conda-forge maintainers
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - pyyaml >=4.0
    - future
    - hist
    - scipy
    - hepdata-validator >=0.3.5
    - imagemagick
    # Treat ROOT as an optional dependency and so don't include it

tests:
  - python:
      imports:
        - hepdata_lib
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip list
      - convert --version
      # TODO: Add test suite checks with ROOT

about:
  summary: Library for getting your data into HEPData
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/HEPData/hepdata_lib
  repository: https://github.com/HEPData/hepdata_lib
  documentation: https://hepdata-lib.readthedocs.io/

extra:
  recipe-maintainers:
    - clelange
    - matthewfeickert
